server:
  port: 8081
spring:
  application:
    name: xxx-service
  cloud:
    httpclientfactories:
      apache:
        enabled: false
      ok:
        enabled: false
    sentinel:
      enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
