spring:
  cloud:
    httpclientfactories:
      apache:
        enabled: false
      ok:
        enabled: false
    sentinel:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'